#include <stdint.h>
#include "image_data_rgb.h" // Generated by the Python script

// Memory Map
#define ACCEL_PUSH  (*(volatile uint32_t*)0x00012024)
#define ACCEL_READ  (*(volatile uint32_t*)0x00012028)
#define UART_TX     (*(volatile uint32_t*)0x00015000)

// Constants for 5x5 RGB
#define IMG_WIDTH   128
#define IMG_HEIGHT  96
#define TOTAL_PIXELS 12288

// 5x5 Warmup: 4 full rows + 2 pixels to reach the center of the window
#define WARMUP 514 

int main() {
    // Loop through the image size PLUS the pipeline warmup latency
    for (int i = 0; i < TOTAL_PIXELS + WARMUP; i++) {
        
        // 1. PUSH into the pipeline
        if (i < TOTAL_PIXELS) {
            ACCEL_PUSH = image_array[i];
        } else {
            // Push dummy black pixels to flush the final lines out of the buffers
            ACCEL_PUSH = 0x00000000; 
        }

        // 2. READ and LOG the results
        if (i >= WARMUP) {
            uint32_t filtered_pixel = ACCEL_READ;
            
            // Send to testbench UART spy (which writes it to simulated_pixels.txt)
            UART_TX = filtered_pixel; 
        }
    }

    // Halt processor when done
    while(1);
    
    return 0;
}