import argparse

import numpy as np
from PIL import Image

def render_hardware_image(txt_filename, output_filename, width, height, scale_factor=1):
    try:
        # 1. Read the pixels from the text file generated by Vivado
        with open(txt_filename, 'r') as f:
            pixels = [int(line.strip()) for line in f.readlines() if line.strip()]
        
        # 2. Ensure we have the correct number of pixels
        expected_pixels = width * height
        if len(pixels) != expected_pixels:
            print(f"Warning: Expected {expected_pixels} pixels, found {len(pixels)}.")
            # Pad with zeros if the simulation stopped early
            pixels.extend([0] * (expected_pixels - len(pixels)))
            pixels = pixels[:expected_pixels]

        # 3. Convert list to an 8-bit unsigned integer numpy array
        # This forces the numbers to strictly be between 0 (Black) and 255 (White)
        img_array = np.array(pixels, dtype=np.uint8).reshape((height, width))

        # 4. Save as a standard Grayscale image ('L' mode)
        base_img = Image.fromarray(img_array, mode='L')

        # 5. SCALE IT UP! 
        # We strictly use Image.Resampling.NEAREST to keep the sharp, raw pixels intact.
        # This prevents Python from adding its own artificial blur!
        new_width = width * scale_factor
        new_height = height * scale_factor
        final_img = base_img.resize((new_width, new_height), Image.Resampling.NEAREST)
        final_img.save(output_filename)
        
        print(f"Success! Hardware accelerated image saved to: {output_filename}")

    except FileNotFoundError:
        print(f"Error: '{txt_filename}' not found.")
        print("Make sure you run the Vivado simulation first!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Render a grayscale pixel text file into an image.")
    parser.add_argument("input", nargs="?", default="simulated_pixels.txt")
    parser.add_argument("output", nargs="?", default="final_output.png")
    parser.add_argument("--width", type=int, default=64)
    parser.add_argument("--height", type=int, default=48)
    parser.add_argument("--scale", type=int, default=1)
    args = parser.parse_args()

    render_hardware_image(args.input, args.output, width=args.width, height=args.height, scale_factor=args.scale)