import sys
import numpy as np
import matplotlib.pyplot as plt

def render_image(filename):
    try:
        # 1. Read the pixels from the text file generated by Vivado
        with open(filename, 'r') as f:
            # Read lines, strip whitespace, and convert to integers
            pixels = [int(line.strip()) for line in f.readlines() if line.strip()]
        
        # 2. Ensure we have exactly 64 pixels for an 8x8 image
        if len(pixels) != 64:
            print(f"Warning: Expected 64 pixels, but found {len(pixels)}.")
            # Pad with zeros if the simulation stopped early
            pixels.extend([0] * (64 - len(pixels)))
            pixels = pixels[:64]

        # 3. Convert the flat list into an 8x8 2D array
        img_array = np.array(pixels).reshape((8, 8))

        # 4. Render the image!
        plt.figure(figsize=(6, 6))
        
        # We use the 'magma' or 'gray' colormap to make the edges pop
        plt.imshow(img_array, cmap='magma', interpolation='nearest') 
        
        plt.title("RV32IM-Vision: Hardware Accelerated Output", fontsize=14, fontweight='bold')
        plt.colorbar(label='Edge Intensity')
        
        # Add gridlines to show the individual pixels clearly
        plt.grid(which='major', color='white', linestyle='-', linewidth=0.5, alpha=0.3)
        plt.xticks(np.arange(-0.5, 8, 1), [])
        plt.yticks(np.arange(-0.5, 8, 1), [])
        
        plt.tight_layout()
        plt.show()

    except FileNotFoundError:
        print(f"Error: '{filename}' not found.")
        print("Make sure you run the Vivado simulation ('make vision') first!")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    # Default to the file generated by Verilog
    render_image('output_pixels.txt')